namespace ArrangingPerformance
{
    public class DemoModel
    {
        public Guid ResponseId { get; set; }
        public Guid ParentResponseId { get; set; }
        public string Name { get; set; }

        // Properties for Q001 to Q100
        public string Q001 { get; set; }
        public string Q002 { get; set; }
        public string Q003 { get; set; }
        public string Q004 { get; set; }
        public string Q005 { get; set; }
        public string Q006 { get; set; }
        public string Q007 { get; set; }
        public string Q008 { get; set; }
        public string Q009 { get; set; }
        public string Q010 { get; set; }
        public string Q011 { get; set; }
        public string Q012 { get; set; }
        public string Q013 { get; set; }
        public string Q014 { get; set; }
        public string Q015 { get; set; }
        public string Q016 { get; set; }
        public string Q017 { get; set; }
        public string Q018 { get; set; }
        public string Q019 { get; set; }
        public string Q020 { get; set; }
        public string Q021 { get; set; }
        public string Q022 { get; set; }
        public string Q023 { get; set; }
        public string Q024 { get; set; }
        public string Q025 { get; set; }
        public string Q026 { get; set; }
        public string Q027 { get; set; }
        public string Q028 { get; set; }
        public string Q029 { get; set; }
        public string Q030 { get; set; }
        public string Q031 { get; set; }
        public string Q032 { get; set; }
        public string Q033 { get; set; }
        public string Q034 { get; set; }
        public string Q035 { get; set; }
        public string Q036 { get; set; }
        public string Q037 { get; set; }
        public string Q038 { get; set; }
        public string Q039 { get; set; }
        public string Q040 { get; set; }
        public string Q041 { get; set; }
        public string Q042 { get; set; }
        public string Q043 { get; set; }
        public string Q044 { get; set; }
        public string Q045 { get; set; }
        public string Q046 { get; set; }
        public string Q047 { get; set; }
        public string Q048 { get; set; }
        public string Q049 { get; set; }
        public string Q050 { get; set; }
        public string Q051 { get; set; }
        public string Q052 { get; set; }
        public string Q053 { get; set; }
        public string Q054 { get; set; }
        public string Q055 { get; set; }
        public string Q056 { get; set; }
        public string Q057 { get; set; }
        public string Q058 { get; set; }
        public string Q059 { get; set; }
        public string Q060 { get; set; }
        public string Q061 { get; set; }
        public string Q062 { get; set; }
        public string Q063 { get; set; }
        public string Q064 { get; set; }
        public string Q065 { get; set; }
        public string Q066 { get; set; }
        public string Q067 { get; set; }
        public string Q068 { get; set; }
        public string Q069 { get; set; }
        public string Q070 { get; set; }
        public string Q071 { get; set; }
        public string Q072 { get; set; }
        public string Q073 { get; set; }
        public string Q074 { get; set; }
        public string Q075 { get; set; }
        public string Q076 { get; set; }
        public string Q077 { get; set; }
        public string Q078 { get; set; }
        public string Q079 { get; set; }
        public string Q080 { get; set; }
        public string Q081 { get; set; }
        public string Q082 { get; set; }
        public string Q083 { get; set; }
        public string Q084 { get; set; }
        public string Q085 { get; set; }
        public string Q086 { get; set; }
        public string Q087 { get; set; }
        public string Q088 { get; set; }
        public string Q089 { get; set; }
        public string Q090 { get; set; }
        public string Q091 { get; set; }
        public string Q092 { get; set; }
        public string Q093 { get; set; }
        public string Q094 { get; set; }
        public string Q095 { get; set; }
        public string Q096 { get; set; }
        public string Q097 { get; set; }
        public string Q098 { get; set; }
        public string Q099 { get; set; }
        public string Q100 { get; set; }

    }
}
